variable "edge_ami" {}
variable "instances_type" {}
variable "region" {}
variable "common_tags" {}
variable "sg_id" {}
variable "transport_subnets" {}
variable "service_subnets" {}
variable "enable_eip_mgmt" {}
variable "ssh_pubkey" {}
variable "sdwan_org" {}
variable "route53_zone" {}
