all:
  vars:
    cloud_infra: "aws"
    region: "eu-west-3"
    vmanage_ip: "<public-ip"
    vmanage_user: "admin"
    vmanage_pass: "C1sco12345"
    vbond: "<public-ip>"
    sdwan_org: "<org-name>"
    sdwan_control_cidr: "10.128.0.0/22"
    viptela_version: "20.9.1"
    vmanage_templates_file: "/ansible/files/vmanage-templates.yml"
    acl_cidr_blocks: '"0.0.0.0/1", "128.0.0.0/1"'
    acl6_cidr_blocks: '"::/0"'
    ssh_pubkey: "<your-public-key>"

  children:
    sdwan_edge:
      hosts:
        cedge1:
          infra: "aws"
          datacenter: "eu-west-3"
          edge_image_id: "ami-0af4ffee3c664012e"
          edge_instance_type: "c5n.large"
          hostname: "cedge1"
          system_ip: "1.1.1.4"
          site_id: "101"
          mrf_region: "101"
          cidr_range: "10.128.4.0/23"
          vpn0_range: "10.128.4.0/24"
          vpn1_range: "10.128.5.0/24"
          uuid: "C8K-E8670B17-3D06-D5BB-4C0E-E6C03E0BCCAB"
          vpn0_ip: "10.128.4.11/24"
          default_gw: "10.128.1.1"
