all:
  vars:
    cloud_infra: "aws"
    cloudinit_type: "v2"
    sdwan_control_cidr: "10.128.0.0/22"
    viptela_version: "20.9.1"
    vmanage_templates_file: "/ansible/files/vmanage-templates.yml"
    acl_cidr_blocks: '"0.0.0.0/1", "128.0.0.0/1"'
    acl6_cidr_blocks: '"::/0"'    
    ntp_servers:
      aws: "169.254.169.123"
      gcp: "metadata.google.internal"
      azure: "pool.ntp.org"
      vmware: "pool.ntp.org"
    terraform_project_path:
      aws:
        edge_instance: "/provision_edge"
        edge_network: "/provision_vpc"

  children:
    sdwan:
      children:
        sdwan_control:
          vars:
            infra: "aws"
            vpn0_gateway: "10.128.1.1"
            sdwan_domain_id: 1
          children:
            vmanage_hosts:
              vars:
                sdwan_personality: vmanage
                sdwan_device_model: vmanage
                mgmt_interface: vpn0_ip
                virl_image_definition: "viptela-manage-20.9.1"
                virl_config_template: "sdwan/user-data.j2"
              hosts:
                vmanage1:
                  sdwan_system_ip: "1.1.1.1"
                  vpn0_ip: "10.128.1.11/24"
                  sdwan_site_id: "1"
                  vpn_instances:
                    - vpn_id: 0
                      interfaces:
                        - if_name: eth1
                          enabled: true
                          ip:
                            address: "10.128.1.11/24"
                          tunnel_interface:
                            allow_service:
                              - all
                      routes:
                        - prefix: 0.0.0.0/0
                          next_hop:
                            address: "10.128.1.1"
                    - vpn_id: 512
                      interfaces:
                        - if_name: eth0
                          enabled: true
                          ip:
                            dhcp_client: true
        sdwan_edge:
          hosts:
            cedge1:
              infra: "aws"
              datacenter: "eu-west-3"
              edge_image_id: "ami-0af4ffee3c664012e"
              edge_instance_type: "c5n.large"
              hostname: "cedge1"
              system_ip: "1.1.1.4"
              site_id: "101"
              mrf_region: "101"
              cidr_range: "10.128.4.0/23"
              vpn0_range: "10.128.4.0/24"
              vpn1_range: "10.128.5.0/24"
              uuid: "C8K-E8670B17-3D06-D5BB-4C0E-E6C03E0BCCAB"
              vpn0_ip: "10.128.4.11/24"
              default_gw: "10.128.1.1"
