- name: Configuration parameters
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Include input vars
      include_vars: ../config/input.json

    - name: Render config for ansible
      template:
        src: "templates/template_ansible_variables.yml"
        dest: "vars.yml"

    - name: Render config for Terraform provision vpc
      template:
        src: "templates/template_terraform_vpc_variables.json"
        dest: "../provision_vpc/my_variables.auto.tfvars.json"

    - name: Render config for Terraform provision edge
      template:
        src: "templates/template_terraform_edge_variables.json"
        dest: "../provision_instances/my_variables.auto.tfvars.json"
