- name: Device token
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Include input vars
      include_vars: vars.yml

    - name: Get vmanage settings
      register: vmanage_settings
      vmanage_settings_get:
        host: "{{ vmanage_host }}"
        password: "{{ vmanage_pass }}"
        user: "{{ vmanage_user }}"

    - name: Setting variables
      set_fact:
        organization: "{{ vmanage_settings.organization }}"
        vbond_host: "{{ vmanage_settings.vbond_host }}"
        vbond_port: "{{ vmanage_settings.vbond_port }}"

    - name: Decommission and get new token
      register: device_details
      vmanage_device_token_get:
        host: "{{ vmanage_host }}"
        password: "{{ vmanage_pass }}"
        user: "{{ vmanage_user }}"
        uuid: "{{ uuid }}"

    - name: Setting variables
      set_fact:
        router: "1"
        system_ip: "{{ system_ip }}"
        token: "{{ device_details.details.serialNumber }}"
        uuid: "{{ device_details.details.uuid }}"

    - name: Generate day0 from template
      template:
        dest: ../provision_instances/cloud-init/edge.cloud_init
        src: templates/edge_cloud_init.j2
