- name: Remove device from vManage
  hosts: "{{ passed }}"
  vars:
  connection: local
  gather_facts: no

  tasks:
    - name: Decommission device
      vmanage_remove_device:
        host: "{{ vmanage_ip }}"
        password: "{{ vmanage_pass }}"
        user: "{{ vmanage_user }}"
        uuid: "{{ uuid }}"
      register: result
      ignore_errors: yes
      when: vmanage_ip is defined and vmanage_ip

    - debug:
        msg: "Result: {{ result }}"
